version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "[INFO] Installing dependencies..."
      - sudo yum install maven
      - mvn --version

  pre_build:
    commands:
      - echo "[INFO] Pre-Build Phase..."

  build:
    commands:
      - echo "[INFO] Build Phase..."
      - mvn clean install

  post_build:
    commands:
      - echo "[INFO] Post-Build Phase..."

artifacts:
  files:
    - target/*.jar
    - aws_scripts/*.sh
    - appspec.yml
  discard-paths: yes
  name: films-webapp-artifact